/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.fretron.vehicleManager.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Vehicle extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Vehicle\",\"namespace\":\"com.fretron.vehicleManager.model\",\"fields\":[{\"name\":\"uuid\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"registrationNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"driverName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bodyType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"chassisType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"carryingCapacity\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uuid;
  @Deprecated public java.lang.CharSequence registrationNumber;
  @Deprecated public java.lang.CharSequence driverName;
  @Deprecated public java.lang.CharSequence bodyType;
  @Deprecated public java.lang.CharSequence chassisType;
  @Deprecated public java.lang.CharSequence carryingCapacity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Vehicle() {}

  /**
   * All-args constructor.
   */
  public Vehicle(java.lang.CharSequence uuid, java.lang.CharSequence registrationNumber, java.lang.CharSequence driverName, java.lang.CharSequence bodyType, java.lang.CharSequence chassisType, java.lang.CharSequence carryingCapacity) {
    this.uuid = uuid;
    this.registrationNumber = registrationNumber;
    this.driverName = driverName;
    this.bodyType = bodyType;
    this.chassisType = chassisType;
    this.carryingCapacity = carryingCapacity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uuid;
    case 1: return registrationNumber;
    case 2: return driverName;
    case 3: return bodyType;
    case 4: return chassisType;
    case 5: return carryingCapacity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uuid = (java.lang.CharSequence)value$; break;
    case 1: registrationNumber = (java.lang.CharSequence)value$; break;
    case 2: driverName = (java.lang.CharSequence)value$; break;
    case 3: bodyType = (java.lang.CharSequence)value$; break;
    case 4: chassisType = (java.lang.CharSequence)value$; break;
    case 5: carryingCapacity = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'registrationNumber' field.
   */
  public java.lang.CharSequence getRegistrationNumber() {
    return registrationNumber;
  }

  /**
   * Sets the value of the 'registrationNumber' field.
   * @param value the value to set.
   */
  public void setRegistrationNumber(java.lang.CharSequence value) {
    this.registrationNumber = value;
  }

  /**
   * Gets the value of the 'driverName' field.
   */
  public java.lang.CharSequence getDriverName() {
    return driverName;
  }

  /**
   * Sets the value of the 'driverName' field.
   * @param value the value to set.
   */
  public void setDriverName(java.lang.CharSequence value) {
    this.driverName = value;
  }

  /**
   * Gets the value of the 'bodyType' field.
   */
  public java.lang.CharSequence getBodyType() {
    return bodyType;
  }

  /**
   * Sets the value of the 'bodyType' field.
   * @param value the value to set.
   */
  public void setBodyType(java.lang.CharSequence value) {
    this.bodyType = value;
  }

  /**
   * Gets the value of the 'chassisType' field.
   */
  public java.lang.CharSequence getChassisType() {
    return chassisType;
  }

  /**
   * Sets the value of the 'chassisType' field.
   * @param value the value to set.
   */
  public void setChassisType(java.lang.CharSequence value) {
    this.chassisType = value;
  }

  /**
   * Gets the value of the 'carryingCapacity' field.
   */
  public java.lang.CharSequence getCarryingCapacity() {
    return carryingCapacity;
  }

  /**
   * Sets the value of the 'carryingCapacity' field.
   * @param value the value to set.
   */
  public void setCarryingCapacity(java.lang.CharSequence value) {
    this.carryingCapacity = value;
  }

  /** Creates a new Vehicle RecordBuilder */
  public static com.fretron.vehicleManager.model.Vehicle.Builder newBuilder() {
    return new com.fretron.vehicleManager.model.Vehicle.Builder();
  }
  
  /** Creates a new Vehicle RecordBuilder by copying an existing Builder */
  public static com.fretron.vehicleManager.model.Vehicle.Builder newBuilder(com.fretron.vehicleManager.model.Vehicle.Builder other) {
    return new com.fretron.vehicleManager.model.Vehicle.Builder(other);
  }
  
  /** Creates a new Vehicle RecordBuilder by copying an existing Vehicle instance */
  public static com.fretron.vehicleManager.model.Vehicle.Builder newBuilder(com.fretron.vehicleManager.model.Vehicle other) {
    return new com.fretron.vehicleManager.model.Vehicle.Builder(other);
  }
  
  /**
   * RecordBuilder for Vehicle instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Vehicle>
    implements org.apache.avro.data.RecordBuilder<Vehicle> {

    private java.lang.CharSequence uuid;
    private java.lang.CharSequence registrationNumber;
    private java.lang.CharSequence driverName;
    private java.lang.CharSequence bodyType;
    private java.lang.CharSequence chassisType;
    private java.lang.CharSequence carryingCapacity;

    /** Creates a new Builder */
    private Builder() {
      super(com.fretron.vehicleManager.model.Vehicle.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.fretron.vehicleManager.model.Vehicle.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.registrationNumber)) {
        this.registrationNumber = data().deepCopy(fields()[1].schema(), other.registrationNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.driverName)) {
        this.driverName = data().deepCopy(fields()[2].schema(), other.driverName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.bodyType)) {
        this.bodyType = data().deepCopy(fields()[3].schema(), other.bodyType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.chassisType)) {
        this.chassisType = data().deepCopy(fields()[4].schema(), other.chassisType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.carryingCapacity)) {
        this.carryingCapacity = data().deepCopy(fields()[5].schema(), other.carryingCapacity);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Vehicle instance */
    private Builder(com.fretron.vehicleManager.model.Vehicle other) {
            super(com.fretron.vehicleManager.model.Vehicle.SCHEMA$);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.registrationNumber)) {
        this.registrationNumber = data().deepCopy(fields()[1].schema(), other.registrationNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.driverName)) {
        this.driverName = data().deepCopy(fields()[2].schema(), other.driverName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.bodyType)) {
        this.bodyType = data().deepCopy(fields()[3].schema(), other.bodyType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.chassisType)) {
        this.chassisType = data().deepCopy(fields()[4].schema(), other.chassisType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.carryingCapacity)) {
        this.carryingCapacity = data().deepCopy(fields()[5].schema(), other.carryingCapacity);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uuid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uuid' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'registrationNumber' field */
    public java.lang.CharSequence getRegistrationNumber() {
      return registrationNumber;
    }
    
    /** Sets the value of the 'registrationNumber' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder setRegistrationNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.registrationNumber = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'registrationNumber' field has been set */
    public boolean hasRegistrationNumber() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'registrationNumber' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder clearRegistrationNumber() {
      registrationNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'driverName' field */
    public java.lang.CharSequence getDriverName() {
      return driverName;
    }
    
    /** Sets the value of the 'driverName' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder setDriverName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.driverName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'driverName' field has been set */
    public boolean hasDriverName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'driverName' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder clearDriverName() {
      driverName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'bodyType' field */
    public java.lang.CharSequence getBodyType() {
      return bodyType;
    }
    
    /** Sets the value of the 'bodyType' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder setBodyType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.bodyType = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'bodyType' field has been set */
    public boolean hasBodyType() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'bodyType' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder clearBodyType() {
      bodyType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'chassisType' field */
    public java.lang.CharSequence getChassisType() {
      return chassisType;
    }
    
    /** Sets the value of the 'chassisType' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder setChassisType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.chassisType = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'chassisType' field has been set */
    public boolean hasChassisType() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'chassisType' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder clearChassisType() {
      chassisType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'carryingCapacity' field */
    public java.lang.CharSequence getCarryingCapacity() {
      return carryingCapacity;
    }
    
    /** Sets the value of the 'carryingCapacity' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder setCarryingCapacity(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.carryingCapacity = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'carryingCapacity' field has been set */
    public boolean hasCarryingCapacity() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'carryingCapacity' field */
    public com.fretron.vehicleManager.model.Vehicle.Builder clearCarryingCapacity() {
      carryingCapacity = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public Vehicle build() {
      try {
        Vehicle record = new Vehicle();
        record.uuid = fieldSetFlags()[0] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.registrationNumber = fieldSetFlags()[1] ? this.registrationNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.driverName = fieldSetFlags()[2] ? this.driverName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.bodyType = fieldSetFlags()[3] ? this.bodyType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.chassisType = fieldSetFlags()[4] ? this.chassisType : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.carryingCapacity = fieldSetFlags()[5] ? this.carryingCapacity : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
